### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by jaedle** [jaedle/mirror-to-gitea#10]

**Comment by CrimsonTome** [comment]
Hi there. I did try to do this via a PR but it would just merge into `master` making the work redundant so: 

You can rename the branch in GitHub
https://github.com/jaedle/mirror-to-gitea/branches
click on the edit pencil and change from `master` to `main`
then once it has renamed you will need to update your local branches and remotes. **everyone who has a clone will need to do this**

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by CrimsonTome** [comment]
Because the branch has been renamed, this will automatically make it the default branch, at least definitely if there are no other branches. Hope this helps and is what you meant :smile:

**Comment by jaedle** [comment]
Hi @CrimsonTome,

thanks for your support. This issue was primarily a reminder. The real change took 10 seconds.

Thank you 🙏
