### ISSUE TITLE
Needs a method to filtering the repositories

### ISSUE THREAD

**Issue by RobertoBochet** [jaedle/mirror-to-gitea#21]
Hi!

I have been looking for a project to do this task for a while, and I thank you for creating it.

I think a system of filters to decide which repos have to be mirrored could be very useful.

**Comment by jaedle** [comment]
Hey @RobertoBochet :wave: 

That sounds like a great feature. :+1: 

What's your filter criteria? Name?

**Comment by jaedle** [comment]
Great work, thanks.

I took the liberty to change the phrasing on the README a little but. I hope that's fine for you :pray:

**Comment by RobertoBochet** [comment]
Thank you so much 😊
