### ISSUE TITLE
Docker entrypoint prevents to run as a task

### ISSUE THREAD

**Issue by RobertoBochet** [jaedle/mirror-to-gitea#23]
Hi!

I think would be useful to allow to run this program as a task.

At this moment `docker-entrypoint.sh` prevents to run this program as single task or in a cronjob, since the entrypoint has no way to terminate in a controlled way.

**Comment by jaedle** [comment]
Hey @RobertoBochet :wave: 

> I think would be useful to allow to run this program as a task.

That was not intended use-case yet, but I completely agree!

> At this moment docker-entrypoint.sh prevents to run this program as single task or in a cronjob, since the entrypoint has no way to terminate in a controlled way.

I will have a look at your PR right away!

**Comment by jaedle** [comment]
Thanks again, merged and released @RobertoBochet :pray:
