### ISSUE TITLE
Feature Request: mirror private repositories

### ISSUE THREAD

**Issue by CrimsonTome** [jaedle/mirror-to-gitea#6]
Any chance that the option to mirror private repos can be a thing? maybe with authenticating via github token or `gh` (github CLI) package.

**Comment by CrimsonTome** [comment]
whoops, there's a PR for this already

**Comment by jaedle** [comment]
Hi @CrimsonTome,

thanks for raising this issue. I believe mirroring private repositories is a feature worth building.

The pr sadly lacks some edge-cases and it may needs to be rewritten.

I will have a look on that feature hopefully during the next week.

**Comment by NelsonDane** [comment]
@CrimsonTome I've created a PR that builds upon the previous one, as well as adding some more options if you're interested.

**Comment by CrimsonTome** [comment]
> @CrimsonTome I've created a PR that builds upon the previous one, as well as adding some more options if you're interested.

Sounds good, you should request a review from @jaedle

**Comment by jaedle** [comment]
Closed by #9 

thanks again for your contribution.
